var details = {
  "response":{
    "code":200,
    "method":"http:\/\/catalog.api.2gis.ru\/doc\/2.0\/catalog\/profile\/profile"
  },
  "result":{
    "total":{
      "total_count":1,
      "filials_count":1
    },
    "data":[
      {
        "id":"141265771881838",
        "name":"Ля Роуз, студия цветов",
        "type":"filial",
        "alias":"lya_rouz_studiya_cvetov",
        "geo":{
          "lon":82.8973495,
          "lat":54.9801322,
          "city_name":"Новосибирск",
          "address":"Карла Маркса площадь, 7",
          "comment":"1 этаж; МФК Сан Сити",
          "register_bc_url":"http:\/\/stat.api.2gis.ru\/?v=2.0&hash=8974jh293BH2J2H9f8BduvDn5A721J34c2A244288B1BB27Bdcec19G4H43I76797"
        },
        "firm":{
          "id":"141274359882737",
          "filials_count":3,
          "name":"Ля Роуз, студия цветов"
        },
        "register_bc_url":"http:\/\/stat.api.2gis.ru\/?v=2.0&hash=c97Ajh293BH24H8ef26duvDn5A72G458545244288B1B478J6cec19G4H3G35899",
        "deletion_time":null,
        "attributes":{
          "general":{
            "label":null,
            "items":[
              {
                "name":"payment_type",
                "type":"enum_multiple",
                "value":[
                  "cash",
                  "visa",
                  "mastercard",
                  "noncash"
                ],
                "label":[
                  "Наличный расчет",
                  "Visa",
                  "MasterCard",
                  "Безналичный расчет"
                ]
              }
            ]
          }
        },
        "ads":{
          "warning":null,
          "comment":null,
          "article":"Студия цветов &laquo;La Rose&raquo; - &laquo;У нас есть то, чего нет у других!&raquo; <br \/>Стильные букеты и композиции; <br \/>Разнообразные горшечные растения; <br \/>Креативное исполнение любой сложности; <br \/>Дизайнерское озеленение в Вашем доме и офисе; <br \/>Торжественное оформление свадеб, корпоративных мероприятий, витрин, банкетов и тематических вечеринок; <br \/>Изысканный стиль с доставкой к Вам! <br \/>В любое место и время; <br \/>Индивидуальный подход к каждому клиенту!",
          "link":null
        },
        "contact_groups":[
          {
            "name":null,
            "contacts":[
              {
                "type":"website",
                "value":"http:\/\/link.2gis.ru\/24144380\/webapi\/20130801\/project1\/141265771881838\/997fjh293BH24H7if18duvDn5A72G4584cd244288B1B478JBcec19G4H7G35899?http:\/\/www.la-rose.ru",
                "register_bc_url":null,
                "comment":null,
                "alias":"www.la-rose.ru"
              },
              {
                "type":"email",
                "value":"info@la-rose.ru",
                "register_bc_url":"http:\/\/stat.api.2gis.ru\/?v=2.0&hash=b977jh293BH24H93fffduvDn5A72G458f68244288B1B478Jdcec19G4HBG35899",
                "comment":null,
                "alias":null
              }
            ]
          },
          {
            "name":null,
            "contacts":[
              {
                "type":"phone",
                "value":"(383) 310-77-10",
                "register_bc_url":"http:\/\/stat.api.2gis.ru\/?v=2.0&hash=7976jh293BH24H79fbAduvDn5A72G45835B244288B1B478Jhcec19G4H5G35899",
                "comment":null,
                "alias":null
              },
              {
                "type":"email",
                "value":"sancity@la-rose.ru",
                "register_bc_url":"http:\/\/stat.api.2gis.ru\/?v=2.0&hash=b97Cjh293BH24H8if83duvDn5A72G458dde244288B1B478JAcec19G4HBG35899",
                "comment":null,
                "alias":null
              }
            ]
          }
        ],
        "schedule":{
          "Mon":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "Tue":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "Wed":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "Thu":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "Fri":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "Sat":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "Sun":{
            "round_the_clock":false,
            "working_hours":[
              {
                "from":"10:00",
                "to":"22:00"
              }
            ]
          },
          "comment":null
        },
        "plus_one":[

        ],
        "external":[

        ],
        "rubrics":{
          "primary":[
            {
              "name":"Цветы"
            }
          ],
          "additional":[
            {
              "name":"Услуги праздничного оформления"
            },
            {
              "name":"Игрушки"
            },
            {
              "name":"Сувениры \/ Подарки"
            }
          ]
        },
        "see_also":[

        ]
      }
    ]
  }
}
